/**
 * Evaluation React Query Hooks
 *
 * Hooks for fetching evaluation summary and per-branch detail data.
 * Data changes infrequently (only on new eval runs), so stale time is 24h.
 */

import { useQuery } from '@tanstack/react-query';
import {
  getEvalSummary,
  getBranchDetail,
  getDatasetStats,
  getDatasetArticles,
  getArticleDetail,
} from '@/lib/api/evaluation';
import type { ArticleQueryParams } from '@/types/evaluation';

/**
 * Query key factory for evaluation data
 */
export const evalKeys = {
  all: ['evaluation'] as const,
  summary: () => [...evalKeys.all, 'summary'] as const,
  branchDetails: () => [...evalKeys.all, 'branch-detail'] as const,
  branchDetail: (branch: string) => [...evalKeys.branchDetails(), branch] as const,
  datasetStats: () => [...evalKeys.all, 'dataset-stats'] as const,
  datasetArticles: (params: ArticleQueryParams) => [...evalKeys.all, 'dataset-articles', params] as const,
  articleDetail: (id: string) => [...evalKeys.all, 'article-detail', id] as const,
};

const TWENTY_FOUR_HOURS = 24 * 60 * 60 * 1000;

/**
 * Hook to fetch the evaluation summary (P/R/F1 per branch per extractor).
 * Data is static — generated by Promptfoo runs — so 24h stale time is appropriate.
 */
export function useEvalSummary() {
  return useQuery({
    queryKey: evalKeys.summary(),
    queryFn: getEvalSummary,
    staleTime: TWENTY_FOUR_HOURS,
  });
}

/**
 * Hook to fetch per-entity-type breakdown for a specific branch.
 * Only enabled when a branch is provided (not for 'all' view).
 */
export function useBranchDetail(branch: string | null) {
  return useQuery({
    queryKey: evalKeys.branchDetail(branch ?? ''),
    queryFn: () => getBranchDetail(branch!),
    enabled: !!branch,
    staleTime: TWENTY_FOUR_HOURS,
  });
}

// --- Dataset hooks (proxy to Spring Boot backend) ---

const ONE_HOUR = 60 * 60 * 1000;

/**
 * Hook to fetch dataset statistics (totals, breakdowns by branch/perturbation/difficulty).
 * Backend data changes infrequently — 1h stale time.
 */
export function useDatasetStats() {
  return useQuery({
    queryKey: evalKeys.datasetStats(),
    queryFn: getDatasetStats,
    staleTime: ONE_HOUR,
  });
}

/**
 * Hook to fetch paginated dataset articles with optional filters.
 * Query key includes params so React Query refetches on filter/page change.
 */
export function useDatasetArticles(params: ArticleQueryParams = {}) {
  return useQuery({
    queryKey: evalKeys.datasetArticles(params),
    queryFn: () => getDatasetArticles(params),
    staleTime: ONE_HOUR,
  });
}

/**
 * Hook to fetch a single article's full details.
 * Only enabled when an ID is provided (for expandable row detail).
 */
export function useArticleDetail(id: string | null) {
  return useQuery({
    queryKey: evalKeys.articleDetail(id ?? ''),
    queryFn: () => getArticleDetail(id!),
    enabled: !!id,
    staleTime: ONE_HOUR,
  });
}
